GSTORAGE_ACCESS_KEY_ID: GOOGDM3WGYYWBOIIQARI
GSTORAGE_SECRET_ACCESS_KEY: SZOOs9dJ/j4Bw4dS2mYR4kxhvkqrEtTLxi6QPEIR
GSTORAGE_HOST: http://howhai.commondatastorage.googleapis.com
GSTORAGE_BUCKET: 'howhai'
